Update
snpptsdev/snppts pull request #133
Opened 2022-08-16 19:24 UTC by IeuanWalker

## Submission description
UI control to auto generate a breadcrumb navigation

2022-08-16 20:23 UTC, jfversluis requested changes
One thing here, the rest looks good!

2022-08-16 20:23 UTC, jfversluis commented on src/Snppts/Snippets/BreadcrumbControl.cs
> +        public string Description => "This is a breadcrumb navigation control https://www.surveymonkey.com/r/maui-ui-challengethat is completely automatic and uses the Navigation stack to get the pag
This description seems a bit funky :D

2022-08-16 20:54 UTC, IeuanWalker commented on src/Snppts/Snippets/BreadcrumbControl.cs
> +        public string Description => "This is a breadcrumb navigation control https://www.surveymonkey.com/r/maui-ui-challengethat is completely automatic and uses the Navigation stack to get the pag
@jfversluis lol not sure how that happened, should be ok now

2022-08-17 06:41 UTC, jfversluis approved these changes

2022-08-17 06:42 UTC, jfversluis commented
Thanks for this great contribution! I think you found the link to claim your stickers already 😜

2022-08-17 06:42 UTC, merged