Personal finance dashboard page
snpptsdev/snppts pull request #49
Opened 2019-11-12 12:16 UTC by ricardoprestes

## Submission description

This is a simple sample dashboard page for a personal finances app. This page contains balance single view, expenses categories chart, next movimentations and credit card bills.

2019-11-12 12:48 UTC, jfversluis commented on src/Snppts/Snppts.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.App">
Please don't change the csproj file :)

2019-11-12 13:05 UTC, jfversluis requested changes
See comment

2019-11-12 13:09 UTC, ricardoprestes commented
Changes in .csproj reverted

2019-11-12 13:17 UTC, jfversluis approved these changes
Looking awesome! Thank you for your contribution!

2019-11-12 13:17 UTC, merged

2019-12-03 17:35 UTC, sthewissen commented
Thanks for contributing to Snppts! Please fill in the following survey to receive your swag :)

https://www.surveymonkey.com/r/88ZQ6G2